# Generated by Django 2.0 on 2018-07-14 06:15

from django.db import migrations, models
import heal.models


class Migration(migrations.Migration):

    dependencies = [
        ('heal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseschedule',
            name='start_time',
            field=models.PositiveIntegerField(db_index=True, default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='courseschedule',
            name='start_date',
            field=models.CharField(db_index=True, default=heal.models.today_format, max_length=32, verbose_name='開課日期'),
        ),
    ]
