# Generated by Django 2.0 on 2018-07-14 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('heal', '0002_auto_20180714_1415'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courseapply',
            old_name='course',
            new_name='schedule',
        ),
    ]
