# Generated by Django 2.0 on 2018-07-14 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heal', '0003_auto_20180714_1446'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='image_url',
            field=models.URLField(blank=True, default=None, null=True),
        ),
    ]
